### PR TITLE
[JENKINS-62176] Add `pre` tag to policy additions as it is missing in Sanitizers

### PR DESCRIPTION
**Pull request by rschluecker**
Since we updated the Markup Formatter Plugin from version 1.5 to 2.0 we noticed that the pre tag in job descriptions is not working anymore.

### CODE REVIEW

**Comment by peteruhnak** [comment]
The pre tag seem to have been explicitly removed in this PR https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/12

> Notably, this drops support for [...] more obscure formatting options (**pre**, cite, samp, center),

However I don't see how `<pre>` is an obscure formatting option. Unless I missed change change in HTML, it still should be the go-to semantic element for showing any multiline preformatted text (well, `<pre><code>`).

Note also that documentation for custom shared libraries uses the configured formatter as well. So removing `<pre>` potentially breaks e.g. code examples in `vars` documentation (which is how I ran into this issue).

**Comment by Janmm14** [comment]
Please readd support for `<pre>`, it is very useful, for example for showing easy-to-copy maven repo and dependny configuration snippets

Also just allow `<cite>`, `<samp>` and `<center>` again, they do not harm too.

**Comment by phoenix384** [comment]
Seems like this PR gets as much attention as the issue JENKINS-61670 I filed since class attributes also don't work anymore. I don't get why they break it and ignore the complaints 👎

**Comment by daniel-beck** [comment]
This seems reasonable.

@Wadeck Can you think of a reason to not allow `pre`?

**Comment by jglick** [comment]
@daniel-beck so do you approve? If you want, I can cut a release with this and #23.

**Pull request merged**
