### PR TITLE
[FIX JENKINS-31616] Prohibit scheme-relative URLs

### PR DESCRIPTION
**Pull request by daniel-beck**
Don't consider URLs that start with `//` to be *onsite*.

### CODE REVIEW

**Comment by daniel-beck** [comment]
@jenkinsci/code-reviewers PTAL

**Comment by olivergondza** [comment]
:+1:

**Comment by batmat** [comment]
LGTM.

Nit-picking: didn't you mean [FIXED instead of FIX](https://wiki.jenkins-ci.org/display/JENKINS/Beginners+Guide+to+Contributing#BeginnersGuidetoContributing-CommitMessages)? @daniel-beck ?

**Comment by daniel-beck** [comment]
@batmat No, the bot (forgot where the repo is) has long ago been changed to also accept `FIX`, and it's shorter.

**Comment by recampbell** [comment]
@daniel-beck Seems like this is ready to merge?

**Comment by daniel-beck** [comment]
@recampbell Sure, just find a maintainer to do that and release the plugin.

**Pull request merged**
